### ISSUE TITLE
Nouvelle monnaie (super_currency)

### ISSUE THREAD

**Issue by vincentux** [duniter/duniter-android-app#20]
Peut on se connecter à la nouvelle monnaie (super_currency) ?
Si oui comment, j'ai essayé (en cliquant sur le +) d'ajouter super_currency@twiced.fr avec le port 9330 mais ça tourne en rond ...

**Comment by naivalf27** [comment]
Non on ne peux pas pour le moment. Le protocole v0.20 n'est pas encore integrer

**Comment by vincentux** [comment]
Ok, merci ;)

**Comment by blavenie** [comment]
Mais l'intégration du protocole 0.20 en cours ! ;)
