### ISSUE TITLE
orthographe

### ISSUE THREAD

**Issue by JeanFe** [duniter/duniter-android-app#58]
Dans paramètres/Règles de la monnaie/ Toile de confiance:

_1ere ligne: _le mot_ "certific**I**ation"  _et même faute à sa droite en bleu_. "1 certific**I**ation"

_4ème phrase:
Quantité maximale de certification**(s)** valide**(s)** …confianc**ep**ar _(manque un espace)_… au**X** règle**S** 

_Dernière ligne: memb**er** _au lieu_ de memb**re**.

_Chapitre "Blockchain"
Dernière ligne: …personalisé**E**

**Comment by blavenie** [comment]
Super, Merci @JeanFe !
