### ISSUE TITLE
Duniter se relance en boucle

### ISSUE THREAD

**Issue by JeanFe** [duniter/duniter-android-app#64]
I just made an updade app duniter  v0.12, since I can not start after entering the login and pin code, it attempts to start but is looped, offering me indefinitely send an email to devs. I tried a new install, but the problem persists.
Je viens de faire une MAJ duniter app v0.12, depuis je ne peux plus le lancer, après la saisie des login et du code pin, il tente de se lancer mais reste en boucle me proposant indéfiniment d'envoyer un mail aux devs. J'ai tenté une résinstall, mais le problème persiste.

**Comment by naivalf27** [comment]
Ce problème sera corriger avec la prochaine mise à jour. Merci de me prévenir si ce n'est pas le cas.
